CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  prenom VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  urlPhoto VARCHAR(255) NOT NULL,
  urlCV VARCHAR(255) NOT NULL,
  gender VARCHAR(5) NOT NULL,
);
